-- local biters = {
-- 	["small-biter"] = true,
-- 	["medium-biter"] = true,
-- 	["big-biter"] = true,
-- 	["behemoth-biter"] = true,
-- 	["leviathan-biter"] = true,
-- }

-- local spitters = {
-- 	["small-spitter"] = true,
-- 	["medium-spitter"] = true,
-- 	["big-spitter"] = true,
-- 	["behemoth-spitter"] = true,
-- 	["leviathan-spitter"] = true,
-- }

-- local snappers = {
-- 	["small-sniper-biter"] = true,
-- 	["medium-sniper-biter"] = true,
-- 	["big-sniper-biter"] = true,
-- 	["behemoth-sniper-biter"] = true,
-- 	["leviathan-sniper-biter"] = true,
-- }
